name: GitHub Actions Demo

on: [pull_request]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: first-step
        run: |
          echo "Hello World!"
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci.py
