name: Github Use Output From Steps
on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'],a) as f:
            print(f'VAL=true', file=f)
        shell: python
      - id: step2
        run: echo "the value is ${{steps.step1.outputs.VAL}}"
